import { Movie, Category } from './types';

export const movies: Movie[] = [
  {
    id: '1',
    title: 'Dune: Part Two',
    originalTitle: 'Dune: Part Two',
    description: 'Paul Atreides unites with Chani and the Fremen while on a warpath of revenge against the conspirators who destroyed his family.',
    backdropUrl: 'https://images.unsplash.com/photo-1626814026160-2237a95fc5a0?q=80&w=1920&h=1080&auto=format&fit=crop',
    posterUrl: 'https://images.unsplash.com/photo-1626814026160-2237a95fc5a0?q=80&w=400&h=600&auto=format&fit=crop',
    releaseYear: 2024,
    rating: '8.6',
    duration: '2h 46m',
    genres: ['Action', 'Adventure', 'Sci-Fi'],
    director: 'Denis Villeneuve',
    cast: ['Timothée Chalamet', 'Zendaya', 'Rebecca Ferguson'],
    kurdishSub: true,
  },
  {
    id: '2',
    title: 'Oppenheimer',
    originalTitle: 'Oppenheimer',
    description: 'The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.',
    backdropUrl: 'https://images.unsplash.com/photo-1440404653325-ab127d49abc1?q=80&w=1920&h=1080&auto=format&fit=crop',
    posterUrl: 'https://images.unsplash.com/photo-1440404653325-ab127d49abc1?q=80&w=400&h=600&auto=format&fit=crop',
    releaseYear: 2023,
    rating: '8.4',
    duration: '3h',
    genres: ['Biography', 'Drama', 'History'],
    director: 'Christopher Nolan',
    cast: ['Cillian Murphy', 'Emily Blunt', 'Matt Damon'],
    kurdishSub: true,
  },
  {
    id: '3',
    title: 'The Dark Knight',
    description: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
    backdropUrl: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?q=80&w=1920&h=1080&auto=format&fit=crop',
    posterUrl: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?q=80&w=400&h=600&auto=format&fit=crop',
    releaseYear: 2008,
    rating: '9.0',
    duration: '2h 32m',
    genres: ['Action', 'Crime', 'Drama'],
    director: 'Christopher Nolan',
    cast: ['Christian Bale', 'Heath Ledger', 'Aaron Eckhart'],
    kurdishSub: true,
  },
  {
    id: '4',
    title: 'Interstellar',
    description: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
    backdropUrl: 'https://images.unsplash.com/photo-1614728263952-84ea256f9679?q=80&w=1920&h=1080&auto=format&fit=crop',
    posterUrl: 'https://images.unsplash.com/photo-1614728263952-84ea256f9679?q=80&w=400&h=600&auto=format&fit=crop',
    releaseYear: 2014,
    rating: '8.7',
    duration: '2h 49m',
    genres: ['Adventure', 'Drama', 'Sci-Fi'],
    director: 'Christopher Nolan',
    cast: ['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain'],
    kurdishSub: true,
  },
  {
    id: '5',
    title: 'John Wick: Chapter 4',
    description: 'John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe and forces that turn old friends into foes.',
    backdropUrl: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?q=80&w=1920&h=1080&auto=format&fit=crop',
    posterUrl: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?q=80&w=400&h=600&auto=format&fit=crop',
    releaseYear: 2023,
    rating: '7.7',
    duration: '2h 49m',
    genres: ['Action', 'Crime', 'Thriller'],
    director: 'Chad Stahelski',
    cast: ['Keanu Reeves', 'Donnie Yen', 'Bill Skarsgård'],
    kurdishSub: true,
  },
  {
    id: '6',
    title: 'Spider-Man: Across the Spider-Verse',
    description: 'Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People charged with protecting its very existence.',
    backdropUrl: 'https://images.unsplash.com/photo-1635805737707-575885ab0820?q=80&w=1920&h=1080&auto=format&fit=crop',
    posterUrl: 'https://images.unsplash.com/photo-1635805737707-575885ab0820?q=80&w=400&h=600&auto=format&fit=crop',
    releaseYear: 2023,
    rating: '8.6',
    duration: '2h 20m',
    genres: ['Animation', 'Action', 'Adventure'],
    director: 'Joaquim Dos Santos',
    cast: ['Shameik Moore', 'Hailee Steinfeld', 'Oscar Isaac'],
    kurdishSub: true,
  },
  {
    id: '7',
    title: 'The Godfather',
    description: 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.',
    backdropUrl: 'https://images.unsplash.com/photo-1594909122845-11baa439b7bf?q=80&w=1920&h=1080&auto=format&fit=crop',
    posterUrl: 'https://images.unsplash.com/photo-1594909122845-11baa439b7bf?q=80&w=400&h=600&auto=format&fit=crop',
    releaseYear: 1972,
    rating: '9.2',
    duration: '2h 55m',
    genres: ['Crime', 'Drama'],
    director: 'Francis Ford Coppola',
    cast: ['Marlon Brando', 'Al Pacino', 'James Caan'],
    kurdishSub: true,
  },
  {
    id: '8',
    title: 'Pulp Fiction',
    description: 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.',
    backdropUrl: 'https://images.unsplash.com/photo-1620173834206-c029bf322dba?q=80&w=1920&h=1080&auto=format&fit=crop',
    posterUrl: 'https://images.unsplash.com/photo-1620173834206-c029bf322dba?q=80&w=400&h=600&auto=format&fit=crop',
    releaseYear: 1994,
    rating: '8.9',
    duration: '2h 34m',
    genres: ['Crime', 'Drama'],
    director: 'Quentin Tarantino',
    cast: ['John Travolta', 'Uma Thurman', 'Samuel L. Jackson'],
    kurdishSub: true,
  }
];

export const categories: Category[] = [
  {
    id: 'trending',
    title: 'دەستەی گشتگیر (Trending Now)',
    movies: movies.slice(0, 4),
  },
  {
    id: 'kurdish-subs',
    title: 'فلیمەکان بە ژێرنووسی کوردی (Kurdish Subtitles)',
    movies: movies.slice(4, 8),
  },
  {
    id: 'action',
    title: 'ئەکشن (Action)',
    movies: movies.filter(m => m.genres.includes('Action')),
  },
  {
    id: 'drama',
    title: 'دراما (Drama)',
    movies: movies.filter(m => m.genres.includes('Drama')),
  }
];

export const featuredMovie = movies[0];
